gitlab: Run tests on Darwin Power9 nodes.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -117,6 +117,12 @@ variables:
 .incremental: &incremental
   REGENT_INCREMENTAL: "1"
 
+.darwin_power9_scheduler: &darwin_power9_scheduler
+  CI_DEBUG_TRACE: "false"
+  SCHEDULER_PARAMETERS: "--nodes=1 --partition=power9"
+  FLEGION_USER: "gitlab-runner-flegion"
+  DARWIN_JOB_TYPE: "power9"
+
 ###
 ### Setup
 ###
@@ -168,6 +174,23 @@ before_script:
         export LAUNCHER="mpirun -n 2 -x TERRA_PATH -x INCLUDE_PATH -x LD_LIBRARY_PATH -x LG_RT_DIR -x USE_RDIR"
       fi
     fi
+  - |
+    if [[ "$DARWIN_JOB_TYPE" = power9 ]]; then
+      if [[ "$CXX" = "g++-6" ]]; then
+        module load openmpi/p9/3.1.4-gcc_6.5.0
+      elif [[ "$CXX" = "g++-7" ]]; then
+        module load openmpi/p9/3.1.4-gcc_7.4.0
+      else
+        echo "Failed to detect Darwin compiler version"
+        false
+      fi
+      module load cmake/3.12.4
+      export OMPI_CXX=${CXX}
+
+      if [[ "$USE_GASNET" -eq 1 ]]; then
+        export LAUNCHER="mpirun -n 2 -x TERRA_PATH -x INCLUDE_PATH -x LD_LIBRARY_PATH -x LG_RT_DIR -x USE_RDIR"
+      fi
+    fi
 
 ###
 ### Tags
@@ -179,6 +202,10 @@ before_script:
 .macos: &macos
   tags:
     - macos
+.darwin_power9: &darwin_power9
+  tags:
+    - darwin-slurm
+    - power9
 
 # For compute-heavy tests:
 .linux_compute: &linux_compute
@@ -215,7 +242,9 @@ before_script:
 .tests: &tests
   script:
     - ./tools/add_github_host_key.sh
-    - grep 'model name' /proc/cpuinfo | uniq -c
+    - grep 'model name' /proc/cpuinfo | uniq -c || true
+    - which $CXX
+    - $CXX --version
     - free
     - ./test.py
   retry:
@@ -630,3 +659,13 @@ n0003_gcc48_cxx98_release_legion_cuda:
 #   <<: [*n0003, *image, *tests]
 #   variables:
 #     <<: [*gcc48, *terra38, *release, *cxx98_normal, *cuda, *regent]
+
+# Darwin Power9 tests:
+darwin_power9_gcc6_cxx14_release_legion:
+  <<: [*darwin_power9, *tests]
+  variables:
+    <<: [*gcc6, *debug, *cxx14_normal, *legion, *darwin_power9_scheduler]
+darwin_power9_gcc7_cxx17_release_legion:
+  <<: [*darwin_power9, *tests]
+  variables:
+    <<: [*gcc7, *debug, *cxx17_normal, *legion, *darwin_power9_scheduler]
